version: "3.8"

services:
    db:
        image: postgis/postgis:16-3.5
        platform: linux/amd64
        container_name: boolder-db
        environment:
            POSTGRES_USER: boolder
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: dump-prod
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U boolder -d dump-prod"]
            interval: 10s
            timeout: 5s
            retries: 5

    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: boolder-web
        command:
            bash -c "bin/rails db:prepare && rm -f tmp/pids/server.pid &&
            bin/dev"
        volumes:
            - .:/rails
            - bundle_cache:/usr/local/bundle
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgis://boolder:${POSTGRES_PASSWORD:-password}@db:5432/dump-prod
            RAILS_ENV: ${RAILS_ENV:-development}
            MAPBOX_DEV_ACCESS_KEY: ${MAPBOX_DEV_ACCESS_KEY}
        depends_on:
            db:
                condition: service_healthy
        stdin_open: true
        tty: true

volumes:
    postgres_data:
    bundle_cache:
    node_modules:
