# Name of your application. Used to uniquely configure containers.
service: austrian-rocks

# Name of the container image.
image: dgtlntv/austrian.rocks

# Deploy to these servers.
servers:
    web:
        - 91.98.152.69
    # job:
    #   hosts:
    #     - 192.168.0.1
    #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
    ssl: true
    host: www.austrian.rocks,austrian.rocks
    # Proxy connects to your container on port 80 by default.
    # app_port: 3000

# Credentials for your image host.
registry:
    # Specify the registry server, if you're not using Docker Hub
    # server: registry.digitalocean.com / ghcr.io / ...
    username: dgtlntv

    # Always use an access token rather than real password (pulled from .kamal/secrets).
    password:
        - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
    arch: amd64
    # Pass in additional build args needed for your Dockerfile.
    # args:
    #   RUBY_VERSION: <%= File.read('.ruby-version').strip %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
    clear:
        # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
        # When you start using multiple servers, you should split out job processing to a dedicated machine.
        SOLID_QUEUE_IN_PUMA: true

        # Set number of processes dedicated to Solid Queue (default: 1)
        # JOB_CONCURRENCY: 3

        # Set number of cores available to the application on each server (default: 1).
        WEB_CONCURRENCY: 2

        # RAILS_MAX_THREADS: 4

        # Match this to any external database server to configure Active Record correctly
        # Use boolder-db for a db accessory server on same machine via local kamal docker network.
        DB_HOST: austrian-rocks-db

        # Log everything from Rails
        RAILS_LOG_LEVEL: debug
    secret:
        - RAILS_MASTER_KEY
        - POSTGRES_PASSWORD

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
aliases:
    console: app exec --interactive --reuse "bin/rails console"
    shell: app exec --interactive --reuse "bash"
    logs: app logs -f
    dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a different ssh user than root
#
ssh:
    user: deploy

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
    db:
        image: postgis/postgis:16-3.5 # <POSTGRES_MAJOR_VERSION>-<POSTGIS_MAJOR_VERSION>
        host: 91.98.152.69
        port: "127.0.0.1:3306:3306"
        env:
            clear:
                POSTGRES_USER: "austrian-rocks"
                POSTGRES_DB: "austrian-rocks-production"
            secret:
                - POSTGRES_PASSWORD
        files:
            - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
        directories:
            - data:/var/lib/postgresql/data
    db_backup:
        image: nmondollot/postgres-backup-s3:16
        host: 91.98.152.69
        env:
            clear:
                SCHEDULE: "@daily" # optional
                BACKUP_KEEP_DAYS: 7 # optional
                S3_REGION: weur
                S3_BUCKET: austrian-rocks
                S3_ENDPOINT: https://1c3e0f0e5d0f66a5afb9722043fda60b.r2.cloudflarestorage.com
                S3_PREFIX: backups
                POSTGRES_HOST: austrian-rocks-db
                POSTGRES_DATABASE: "austrian-rocks-production"
                POSTGRES_USER: "austrian-rocks"
            secret:
                - S3_ACCESS_KEY_ID
                - S3_SECRET_ACCESS_KEY
                - POSTGRES_PASSWORD
                # - PASSPHRASE  # optional for encrypted backups
